# Shared helpers for the noise-suppression engine build scripts
# (build-*-worklet.sh). Sourced, not executed.
#
# Each engine ships as content-hashed files under vendor/<engine>/
# plus a generated manifest module the loader imports. /plugins/ assets are
# served with long-lived immutable caching, so every rebuild must change the
# URLs — hence the hashes.

hash8() {
  sha256sum "$1" | cut -c1-8
}

# bundle_worklet <engine> <out_file>
bundle_worklet() {
  local engine="$1"
  local out="$2"
  cd "${GEM_ROOT}"
  pnpm install --silent
  pnpm exec esbuild "${GEM_ROOT}/src/${engine}-worklet/noise-suppression-processor.js" \
    --bundle --format=iife --minify --outfile="${out}"
}

# emit_ns_assets <engine> <worklet_bundle> <wasm_file> [model_file]
#
# Copies the artifacts into vendor/<engine>/ with content-hashed
# names and regenerates manifests/<engine>.js.
emit_ns_assets() {
  local engine="$1"
  local bundle="$2"
  local wasm="$3"
  local model="${4:-}"

  local output_dir="${GEM_ROOT}/vendor/${engine}"
  local manifest="${GEM_ROOT}/manifests/${engine}.js"

  rm -rf "${output_dir}"
  mkdir -p "${output_dir}" "$(dirname "${manifest}")"

  local worklet_name="${engine}-worklet.$(hash8 "${bundle}").js"
  local wasm_name="${engine}.$(hash8 "${wasm}").wasm"
  install -m 644 "${bundle}" "${output_dir}/${worklet_name}"
  install -m 644 "${wasm}" "${output_dir}/${wasm_name}"

  {
    echo "// Generated by scripts/build-${engine}-worklet.sh — do not edit."
    echo "// Filenames relative to the plugin's public javascripts dir (the gem's"
    echo "// vendor dir); the loader picks the base (app origin or CDN) at runtime."
    echo "export const WORKLET_FILE = \"${engine}/${worklet_name}\";"
    echo "export const WASM_FILE = \"${engine}/${wasm_name}\";"
    if [ -n "${model}" ]; then
      local model_name="${engine}-model.$(hash8 "${model}").bin"
      install -m 644 "${model}" "${output_dir}/${model_name}"
      echo "export const MODEL_FILE = \"${engine}/${model_name}\";"
    fi
  } > "${manifest}"

  pnpm exec prettier --write --log-level silent "${manifest}"

  echo "==> Build complete!"
  ls -la "${output_dir}"
  echo "    ${manifest}"
}
